### ISSUE TITLE
Concurrent implementation

### ISSUE THREAD

**Issue by jpic** [jonashaag/django-addanother#1]
Hi

I failed to find your repo before making my own implementation. This issue is about removing my duplicate repo. The two implementations differ though, so I'd like to know your thoughts about the possibilities we have to unite the repos.

Here are the differences:
- instead of a mixin, we provide [AddAnotherWidgetWrapper](https://github.com/yourlabs/django-addanother/blob/master/addanother/widgets.py#L28), which is inspired from [django.contrib.admin.widgets.RelatedFieldWidgetWrapper](https://github.com/django/django/blob/926e90132dc15d76bb8d16e2f9f1279566cac3c3/django/contrib/admin/widgets.py#L246),
- therefore, it uses [django's RelatedObjectLookups.js](https://github.com/django/django/blob/926e90132dc15d76bb8d16e2f9f1279566cac3c3/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js),
- like django's RelatedFieldWidgetWrapper, it uses a template, although i'm open on that, I thought a template would make it easy to override and that would be the reason why it's done this way in the admin but i'm open to changing that

What do you think ? Would you prefer to upgrade to the newer implementation, add it and support both, or just keep it in two separate apps ?

Best

**Comment by jonashaag** [comment]
Your app looks nice, there are a few things in there that I didn't think about. I'm all for a merge, I'll add some comments to your code, maybe we can even get rid of my implementation entirely.

**Comment by guettli** [comment]
@jonashaag can I help you to get the merge done?

**Comment by jonashaag** [comment]
What kind of help are you looking for?

**Comment by guettli** [comment]
@jonashaag My goal is to get the django-addanother version from jpic (yourslab) installable via pip from pypi.

This is my issue there: https://github.com/yourlabs/django-addanother/issues/2

You said:

> I'm all for a merge, I'll add some comments to your code, maybe we can even get rid of my implementation entirely.

Of course the version from yourslab could be uploaded to a different name. But if you would like, to merge ... nice. What is missing to get it done?

The version from yourslab looks good. Is there in our implementation that you are missing from the yourslab version?

**Comment by jonashaag** [comment]
> What is missing to get it done?
> 
> The version from yourslab looks good. Is there in our implementation that you are missing from the yourslab version?
- Make the changes I suggested in my review there
- Add source code documentation
- Add user documentation
- Get rid of jQuery dependency

Also I'll have to have a look at how it actually looks in the browser. Haven't done that yet.

**Comment by guettli** [comment]
solved by https://github.com/jonashaag/django-addanother/pull/3
