### ISSUE TITLE
Why no "edit" button as well ?

### ISSUE THREAD

**Issue by olivierdalang** [jonashaag/django-addanother#11]
Hi !

This app is great, nice and simple.
Did you consider allowing to add the "edit" button as well ?

It could be either specific wrapper classes, or an argument to choose between add link only, edit link only, or both links.

Thanks !

**Comment by jonashaag** [comment]
I'd like to see an actual implementation of that!

**Comment by olivierdalang** [comment]
I'm not sure what you mean ?
Here's an example of what I'm talking about (in the django-autocomplete-light demo) :
http://dal-yourlabs.rhcloud.com/admin/select2_foreign_key/testmodel/53/change/

For the record, here's why I'm asking for this :
https://github.com/yourlabs/django-autocomplete-light/issues/648#issuecomment-221844221

**Comment by jonashaag** [comment]
I'd like to see some code that implements this feature in django-addanother. My guess is that it's actually very simple to implement, but I'm not quite sure. The code could function as a basis for a decision if we want to include it in the project.

**Comment by jpic** [comment]
EPIC :guitar:
