### ISSUE TITLE
django-addanother disables django-smart-selects

### ISSUE THREAD

**Issue by Vinterand** [jonashaag/django-addanother#22]
Hi,

My project relies heavily on django-smart-selects. 
After i integrated django-addanother into my project, django-smart-selects (out of admin) stopped working. I think It's something related to javascript in the view created by smart-selects which is being overwritten or deleted by addanother. 
I use overridden valid_form() method like this in my views:

``` python
from django_addanother.views import PopupMixin
class LuogoCreate(PopupMixin, CreateView):
    success_url = reverse_lazy("ipms:nuovo_luogo")

[...]

 def valid_form(self, form, addanother, savecontinue, delete):
        self.object = form.save()
        if addanother:
            return redirect("nrms:nuovo_luogo")
        elif savecontinue:
            return redirect("nrms:modifica_luogo", self.object.id)
        elif delete:
            return redirect("nrms:elimina_luogo", self.object.id)
        elif self.is_popup():
            return self.respond_script(self.object)
        else:
            return redirect("nrms:luoghi")
```

Any hints?

**Comment by jonashaag** [comment]
Hi and thanks for the report. Could you please come up with a minimal reproducing example project? You can try to reproduce the issue in our test project for example.
