### ISSUE TITLE
Update fields of the same form

### ISSUE THREAD

**Issue by CleitonDeLima** [jonashaag/django-addanother#28]
How do I update fields of the same form using the same model?

Example:

```python
...
'client': AddAnotherEditSelectedWidgetWrapper(
      forms.Select,
      reverse_lazy('client-create'),
      reverse_lazy('client-update', args=['__fk__'])
),
 'sender': AddAnotherEditSelectedWidgetWrapper(
      forms.Select,
      reverse_lazy('client-create'),
      reverse_lazy('client-update', args=['__fk__'])
)
```

**Comment by jonashaag** [comment]
Could you give a bit more context please? I don't understand what you're trying to accomplish and what your problems are.

**Comment by CleitonDeLima** [comment]
Did not speak very well in English (use translator), sorry.

OK,

Today in django I have a model with two foreign key fields (both comes from the Client model) that use the same model. As in the example above, I have the sender and client (recipient, I made a mistake in declaring this). If I use the add popup in the sender field, it will refresh the select normally, but the select from the client field does not update. This occurs in Django admin as well.

This is discussed here:
https://code.djangoproject.com/ticket/11803

Do you know of any solution to this?

**Comment by jonashaag** [comment]
I see. Since django-addanother uses the admin JS, this is not something we'll fix in this project. Please try to contribute to the Django ticket.

**Comment by CleitonDeLima** [comment]
In Django2.0 this works with autocomplete :D
https://docs.djangoproject.com/en/2.0/releases/2.0/#django-contrib-admin
