### ISSUE TITLE
Edit-button doesn't get the fk using DAL

### ISSUE THREAD

**Issue by dwasyl** [jonashaag/django-addanother#30]
Hey there,

The widget works great for adding new values, no problem at all. But, the Edit button seems to fail. I'm wrapping the DAL widget and when I select a value, the __fk__ value is never populated, and the Edit button remains disabled. Is there some trick with DAL?

Edit: To clarify, when you create a new object via `addanother` and return to the page the `id` for the new item is populated correctly, but when you pick a new one from the DAL widget, that id value never gets updated.

Cheers

**Comment by jonashaag** [comment]
Maybe a bug, could you try to debug the issue?

**Comment by dwasyl** [comment]
@jonashaag When the item is selected on form load (i.e. already chooosen) the edit link loads okay, but when the item is selected dynamically on the page the `Edit` icon's URL never gets updated with the correct FK. Where should this be happening? Or is this something I need to hookup manually?

**Comment by jonashaag** [comment]
It's some JS shipped with Django. Have a look at the JS files in `widgets.py` of this project. Try to debug that Django JS.

**Comment by dwasyl** [comment]
Yeah, the Django JS isn't picking up the change in select value as done by DAL. I'm wondering if it's related to multiple jQuery versions being loaded (Django Admin & mine). DAL is loaded into my jQuery namespace not the Django admin.
