### ISSUE TITLE
How to add multiple stack popups?

### ISSUE THREAD

**Issue by HeroSony** [jonashaag/django-addanother#32]
Hi, how to implement multiple stack popup?

**Comment by jonashaag** [comment]
What do you mean?

**Comment by jpic** [comment]
I suppose they are talking about:
"Click add another, in popup there is another form with add another, click add another in the popup"
I thought that was supposed to work

**Comment by HeroSony** [comment]
@jpic That's what I am talking about.
I forgot adding {{ form.media }} to current popup.
Now I can fixed it.
Thank for your quickly response...
@jonashaag and @jpic
