### ISSUE TITLE
Error when using CreatePopupMixin on Django 3.0

### ISSUE THREAD

**Issue by dewes** [jonashaag/django-addanother#36]
In Django 3.0 they removed six from django.utils. https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

Error: 

File "/usr/local/lib/python3.7/site-packages/django_addanother/views.py", line 6, in <module>
from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.7/site-packages/django/utils/__init__.py)

**Comment by jonashaag** [comment]
PR welcome! (Should keep Python 2.7 compat)

**Comment by CleitonDeLima** [comment]
@jonashaag  

I think this was resolved with this [commit](https://github.com/jonashaag/django-addanother/commit/0295be0bf57e9b2a977c40b9e37a08e0dd9b58aa)

**Comment by jonashaag** [comment]
Oops. Right. Closing then
