### ISSUE TITLE
Formset compatibility

### ISSUE THREAD

**Issue by paul-s-johnson** [jonashaag/django-addanother#45]
Jonas, thank you for creating this and putting this out there for others to use. I was able to install it and get the included demo project running with no problem. The demo is very useful to answer questions.

I am trying to get django-addanother to run correctly with a Django formset. It works fine for the first form in the formset, but in subsequent forms in the formset, upon closing, the popup window inserts the new record into the first form in the formset only. I'm not sure if there is an existing way to create the desired behavior. Is it possible or does django-addanother not accommodate formsets?

Thanks, Paul

**Comment by paul-s-johnson** [comment]
I have to put an addendum on here. The formset page I'm working is tweaked to dynamically add forms to the formset as needed with Javascript. "Add" does not work with those dynamically added with this feature, but if the formset is initialized with something like the following:

`inlineformset_factory(Title, TitleCreator, form=TitleCreatorsForm, extra=4)`

(N.B. `extra=4` is the parameter that creates 4 blank forms in the formset)

then it will work with those four forms. This is a good enough workaround for now for the particular thing I'm working on.

**Comment by jonashaag** [comment]
Thanks for reporting this! Do you know if that works in the Django admin?
