### ISSUE TITLE
Error on migrate in test_project

### ISSUE THREAD

**Issue by fproldan** [jonashaag/django-addanother#5]
Hi! i just cloned the repo and when i try to run the migrate command, the console throws the follow error:
django.db.utils.OperationalError: no such table: auth_group

Any idea?

Thanks!

**Comment by jpic** [comment]
Very interresting, it looks like a bug in Django​, I could reproduce this
without django-addanother, with just this in forms.py:

```
from django.contrib.auth.models import Group, User
from django.core.urlresolvers import reverse_lazy
from django import forms


class TestForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'groups']
        widgets = {
            'groups': forms.SelectMultiple(choices=Group.objects.all()),
        }
```

**Comment by jpic** [comment]
Seems like that's the piece of code causing the issue in Django:

```
class Select(Widget):
    allow_multiple_selected = False
    def __init__(self, attrs=None, choices=()):
        super(Select, self).__init__(attrs)
        # choices can be any iterable, but we may need to render this widget
        # multiple times. Thus, collapse it into a list so it can be consumed
        # more than once.
        self.choices = list(choices)
```

This casts choices to list which executes the queryset at django
startup, before the table has been created.

I don't think we want the queryset here to be evaluated at django
startup, but rather when the widget is rendered for example.

Could anybody confirm this is a bug in Django ?

Thanks !!

**Comment by jonashaag** [comment]
I don't think this can be considered a bug, it's simply Python semantics that everything is executed immediately even on class level. Well maybe Django should throw a different error, what version of Django are you using?

**Comment by jonashaag** [comment]
Fixed
