### ISSUE TITLE
Django 4.1 support

### ISSUE THREAD

**Issue by N1K1TAS95** [jonashaag/django-addanother#54]
Hi there!
Since I've updated Django from version `4.0.7` to `4.1`, django-addanother does not work properly.
The popup, when I'm click on the plus button, does not show up, but instead it just opens another page (in the same browser tab).
Also, in the opened page, when i add new object, it throws an error:
```
popup_response.js:13` Uncaught TypeError: Cannot read properties of null (reading 'dismissAddRelatedObjectPopup')
at popup_response.js:13:16
```
I'll be glad to supply other info or code if requested.

**Comment by jonashaag** [comment]
Thanks for the report. Do you think you could try to submit a fix?

**Comment by N1K1TAS95** [comment]
@jonashaag I'll try to find a fix. But I can't promise much, I'm not so good 😅.

**Comment by N1K1TAS95** [comment]
@jonashaag I've added a new PR #55 . I've found a fix. It woks perfectly with Django 4.1 and Django 4.0.7.

**Comment by N1K1TAS95** [comment]
@jonashaag Is it possible to update [PIP package](https://pypi.org/project/django-addanother/) ? 😁
