### ISSUE TITLE
Catch up with Django 4.1 features

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/django-addanother#56]
- https://github.com/django/django/pull/15301
- https://github.com/django/django/pull/15363

**Comment by N1K1TAS95** [comment]
@jonashaag would you be able to update the [PIP ](https://pypi.org/project/django-addanother/) package soon?

**Comment by jonashaag** [comment]
Done!

**Comment by N1K1TAS95** [comment]
@jonashaag Thanks!!!

**Comment by dwasyl** [comment]
@jonashaag it looks like pypi got three copies 2.2.0, 2.2.1 and 2.2.2 none of which are tagged as releases or in the changelog. Is it possible to update the change log and tags/releases on here as well? I spent some time trying to make sure they were legit which could be avoided.

**Comment by dmenisdev** [comment]
I assume looking at some commit description that Django versions >1.10 are support.

Is that assumption correct?

If yes, can we update the documentation (https://github.com/jonashaag/django-addanother/blob/master/docs/index.rst) to reflect this? 

Thanks.
