### ISSUE TITLE
'AddAnotherWidgetWrapper' object has no attribute 'choices'

### ISSUE THREAD

**Issue by mmoravcik** [jonashaag/django-addanother#57]
Hi I am getting the above error, I am running Django 4.1.1 and setup the widget as follows:

     form.fields['venue'].widget = AddAnotherWidgetWrapper(
            forms.Select,
            reverse_lazy('create-venue'),
      )

Are all the Django 4x related fixes releases in pypi? I am using 2.2.2 version (the last tag I can see here is 2.1.0)
Thank you

**Comment by jonashaag** [comment]
Doesn’t seem related to Django update. Maybe misuse of the API or another bug?

**Comment by mmoravcik** [comment]
OK so this works when added in the form.Meta (as per docs)


```
class EventForm(forms.ModelForm):
    class Meta:
        ...
        widgets = {
            'venue': AddAnotherWidgetWrapper(
                forms.Select,
                reverse_lazy('dashboard:venue-create'),
            )
        }
```

but it doesn't when used in the view.get_form()

```
class Event(CreateView):
    ....
    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        form.fields['venue'].widget = AddAnotherWidgetWrapper(
          forms.Select,
          reverse_lazy('create-venue'),
        )
        return form
```
