### ISSUE TITLE
bug? or im doing something wrong? help appreciated

### ISSUE THREAD

**Issue by efthimios-karbelas** [jonashaag/django-addanother#58]
First of all thanks for the amazing tool!

I'm trying to use the edit/new wrapper for a select 2 widget, the multiple select to be precise .

What i'm doing is

```
#urls

path("models/creator/add", views.CreatorAddView.as_view(), name="creator_add"),
path("models/creator/edit/<pk>", views.CreatorEditView.as_view(), name=creator_edit"),

# form

widgets = {
    "creator" : Select2MultipleAddAnotherEditSelected(
        reverse_lazy("main:creator_add"),
        reverse_lazy("main:creator_edit", args=["__fk__"]),
    )
}
```

The create works fine, but the edit does some weird behavior ...

![image](https://user-images.githubusercontent.com/117673975/215173845-5d877b20-9ee8-42b7-a7c7-399433472c37.png)

The data are stored in the database, so in a refresh of the page they show, but the selected value isn't changing, its just appended on the input field and its not editable or select-able. 

Also, since the field is multi-select, if there are 2 or more values selected, the edit button view gets all their id as input. I get that's probably intended, but any way to disable it if none or 2+ are selected? I'm using a UpdateView.

Thanks for any help!

**Comment by jonashaag** [comment]
What version of Django are you using? I haven’t used this library for a couple of years — you’ll have to invest some time debuting this.

**Comment by efthimios-karbelas** [comment]
I'm using the latest versions of django (4.1.5) , django-select2 (8.0.0) and django-addanother (2.2.2). I did some tests couple months back and it worked fine, but now i cant get it to work. So i thought its some update that broke stuff. But downgrading django and select2 didnt fix it...

**Comment by jonashaag** [comment]
Note that there is a fix on master that’s not yet released IIRC

**Comment by efthimios-karbelas** [comment]
i think its in pypi already. i went through with the debugger to try to solve this, but i guess im not good enough haha. any help appreciated.

**Comment by jonashaag** [comment]
Do other widgets work correctly? Eg the one without editing, or without select2, or with single select only

**Comment by efthimios-karbelas** [comment]
ok, turns out, django's edit on foreign keys doesn't work on multi-select fields, well the edit works, but the javascript that handles the select update isn't coded to handle multi-select. i tried to override a lot of django's and select2 built-in js handlers, but it's just not worth it. i decided to make a different page to add/edit/delete models that will appear later on my drop-downs. sorry for the trouble i may have caused.

**Comment by jonashaag** [comment]
Good to know! Does this not work in the Django admin either? Because if it works in the admin we should also be able to get it to work here.

**Comment by jonashaag** [comment]
Closing due to lack of feedback
