### ISSUE TITLE
Docs: view.is_popup

### ISSUE THREAD

**Issue by guettli** [jonashaag/django-addanother#8]
I don't get the "if" in this template. What does `<nav>...</nav>` mean here?

If the view is a popup the navigation should be hidden....

Or is there a negation missing in the template snippet?

{{{
You may want to hide header, footer and navigation elements for the popups. When the create view is opened in a popup, the view.is_popup template variable is set:

```
{% if view.is_popup %}
  <nav>...</nav>
{% endif %}
```

}}}
http://django-addanother.readthedocs.org/en/latest/usage.html?highlight=popup#make-your-view-popup-compatible

**Comment by jonashaag** [comment]
> Or is there a negation missing in the template snippet?

Yes, thanks for the report, I'll fix this real quick
