### ISSUE TITLE
Docs: Make your view popup-compatible

### ISSUE THREAD

**Issue by guettli** [jonashaag/django-addanother#9]
From: http://django-addanother.readthedocs.org/en/latest/usage.html#make-your-view-popup-compatible

You use **one** CreateView for normal adding and for adding inside the pop-up.

This results in an unavoidable "if" in the template (hiding the navigation stuff inside the poup)

I like the goal "conditionless code" even if this means typing in some more characters.

I will use **two** CreateViews:
- for normal adding
- for adding inside the popup.

What do you think?

**Comment by jonashaag** [comment]
Nice idea. I'd like to get feedback from some more users one this first.

**Comment by jonashaag** [comment]
For the time being, this can be implemented by overwriting `get_template_names` accordingly

**Comment by guettli** [comment]
I thought about this again.

Imagine you have 20 views which provide the content for a pop-up used by add-another.
Then you would need 20 times 2 views. The solutions from the docs would only need 20 times 1 views.

I think your solution from the docs is better.

But a note in the docs would be nice. Maybe add this below `{% if not view.is_popup %} <nav>...nav>{% endif %}`

{{{
If you don't like conditions in your templates, you can avoid this `if` and provide a custom view to AddAnotherWidgetWrapper which does render appropriate HTML for pop-ups (with out navigation bar ...).

We prefer the condition in the template, since this is less code if you have several views which gets used by the add-another widget.
}}}

**Comment by jonashaag** [comment]
> But a note in the docs would be nice.

The `get_template_names` pattern is so basic it hardly justifies a hint in the docs, imo.

**Comment by guettli** [comment]
ok. It is not that important to me.
